# Builds using pip and tests using pytest

name: Linux Basic CPU

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        mkdir build
        pushd build
        cmake .. -DCUDA=0
        make -j2
    - name: Run Simple Test Script
      run: bash ./ci/oxDNA-quick_input.sh
